describe('Criação,Atualização e deleção de funcionário', () => {
    it('Registrar um novo funcionário', () => {
      //cy.login('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList','Admin','admin123')
      cy.get('.orangehrm-header-container > .oxd-button').click()
      //cy.get('.--name-grouped-field > :nth-child(1) > :nth-child(2) > .oxd-input').type('trabalho')
      cy.get(':nth-child(2) > :nth-child(2) > .oxd-input').should('be.visible').type('pratico')
      cy.get(':nth-child(3) > :nth-child(2) > .oxd-input').should('be.visible').type('devops')
      cy.get('.oxd-switch-input').should('be.visible').click()
      cy.get(':nth-child(4) > .oxd-grid-2 > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('nu user')
      cy.get('.user-password-cell > .oxd-input-group > :nth-child(2) > .oxd-input').type('123456a')
      cy.get('.oxd-grid-2 > :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('123456a')
      cy.get('.oxd-button--secondary').click()
      cy.wait(2000)
      cy.get('.oxd-toast').should("include.text", "Successfully")
    });

    it('Atualizar detalhes do funcionário', () => {
        /cy.login('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList','Admin','admin123')
        cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-autocomplete-wrapper > .oxd-autocomplete-text-input > input').type('trabalho pratico devops')
        //cy.get('.oxd-autocomplete-option').click()
        cy.wait(1000)
        cy.get('.oxd-form-actions > .oxd-button--secondary').click({force: true})
        cy.wait(2000)
        cy.get('.oxd-table-cell-actions > :nth-child(2)').click()
        cy.get(':nth-child(1) > .oxd-grid-3 > .oxd-grid-item > .oxd-input-group > :nth-child(2) > .oxd-input').type('nuuu')
        cy.get(':nth-child(3) > :nth-child(1) > :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('0321')
        cy.get(':nth-child(3) > :nth-child(2) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('61901-280')
        cy.get(':nth-child(3) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('41909922')
        cy.get(':nth-child(3) > :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('9929292')
        cy.get(':nth-child(1) > :nth-child(2) > .oxd-radio-wrapper > label > .oxd-radio-input').click({force: true})
        cy.get(':nth-child(7) > .oxd-grid-3 > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('No')
        cy.get(':nth-child(2) > .oxd-checkbox-wrapper > label > .oxd-checkbox-input > .oxd-icon').click({force: true})
        cy.get(':nth-child(1) > .oxd-form > .oxd-form-actions > .oxd-button').click()
        cy.get('.oxd-toast').should("include.text", "Successfully Updated")
    })

    it('Remover funcionário', () => {
        //cy.login('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList','Admin','admin123')
        cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-autocomplete-wrapper > .oxd-autocomplete-text-input > input').type('trabalho pratico devops')
        //cy.get('.oxd-autocomplete-option').click()
        cy.wait(1000)
        cy.get('.oxd-form-actions > .oxd-button--secondary').click({force: true})
        cy.wait(2000)
        cy.get('.oxd-table-cell-actions > :nth-child(1)').click()
        cy.get('.oxd-button--label-danger').click()
        cy.wait(1000)
        cy.get('.oxd-toast').should("include.text", "Successfully")
    })
});